disableKinds = ['rss','sitemap','taxonomy','term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
baseURL = "https://site.com/"
contentDir = "content/en"

[languages.ru]
baseURL = "https://site.ru/"
contentDir = "content/ru"
